//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBinder.CLang.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CLangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CLangResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBinder.CLang.Resources.CLangResources", typeof(CLangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;cstring&gt;
        ///#include &lt;string&gt;
        ///#include &lt;stdexcept&gt;
        ///#include &lt;cstdlib&gt;
        ///#endif
        ///
        ///#ifdef WIN32
        ///extern &quot;C&quot; __declspec(dllimport) void * __stdcall CoTaskMemAlloc(size_t cb);
        ///#else
        ///
        ///extern &quot;C&quot;
        ///{
        ///    struct cstring16
        ///    {
        ///        char16_t* string;
        ///        intptr_t length;
        ///    };
        ///
        ///    struct cstring
        ///    {
        ///        char* string;
        ///        intptr_t length;
        ///    };
        ///
        ///    inline cstring16 alloc_cstring16(const char16_t* str, size_t len)
        ///    {
        ///        if (str == nullptr)
        ///            return { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cstrings_h {
            get {
                return ResourceManager.GetString("cstrings_h", resourceCulture);
            }
        }
    }
}
