//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBinder.Apple {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjCResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjCResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBinder.Apple.ObjC.Resources.ObjCResources", typeof(ObjCResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * SPDX-FileCopyrightText: (C) 2020 Francesco Pretto &lt;ceztko@gmail.com&gt;
        /// * SPDX-License-Identifier: MIT-0
        /// */
        ///
        ///#ifndef CBHANDLEDOBJECT_HEADER
        ///#define CBHANDLEDOBJECT_HEADER
        ///#pragma once
        ///
        ///#import &quot;cboclibdefs.h&quot;
        ///#import &lt;Foundation/Foundation.h&gt;
        ///#import &quot;CBHandleRef.h&quot;
        ///
        ///OBJC_CODEBINDER_API @protocol CBIObjectFinalizer
        ///@end
        ///
        ///OBJC_CODEBINDER_API @interface CBHandledObjectFinalizer : NSObject&lt;CBIObjectFinalizer&gt;
        ///{
        ///    @private void* _handle;
        ///}
        ///@end
        ///
        ///OBJC_CODEBINDER_API @interface CBFin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CBHandledObject_h {
            get {
                return ResourceManager.GetString("CBHandledObject_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * SPDX-FileCopyrightText: (C) 2020 Francesco Pretto &lt;ceztko@gmail.com&gt;
        /// * SPDX-License-Identifier: MIT-0
        /// */
        ///
        ///#ifndef CBHANDLEDOBJECT_INTERNAL_HEADER
        ///#define CBHANDLEDOBJECT_INTERNAL_HEADER
        ///#pragma once
        ///
        ///#import &quot;../Support/CBHandledObject.h&quot;
        ///
        ///@interface CBHandledObjectFinalizer ()
        ///    - (id)init;
        ///
        ///    -(void)dealloc;
        ///
        ///    -(void)freeHandle:(void*)handle;
        ///
        ///    @property(nonatomic) void* handle;
        ///    -(void*)handle;
        ///    -(void)setHandle:(void*)value;
        ///@end
        ///
        ///@interface CBFinalizableO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CBHandledObject_Internal_h {
            get {
                return ResourceManager.GetString("CBHandledObject_Internal_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * SPDX-FileCopyrightText: (C) 2020 Francesco Pretto &lt;ceztko@gmail.com&gt;
        /// * SPDX-License-Identifier: MIT-0
        /// */
        ///
        ///#import &quot;CBHandledObject.h&quot;
        ///#import &quot;../Internal/CBHandledObject.h&quot;
        ///#import &quot;../Internal/CBOCBinderUtils.h&quot;
        ///#import &quot;CBException.h&quot;
        ///
        ///@implementation CBHandledObjectFinalizer
        ///    - (id)init
        ///    {
        ///        self = [super init];
        ///        if (self == nil)
        ///            return nil;
        ///        return self;
        ///    }
        ///
        ///    -(void)dealloc
        ///    {
        ///        [self freeHandle:_handle];
        ///    }
        ///
        ///    - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CBHandledObject_mm {
            get {
                return ResourceManager.GetString("CBHandledObject_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * SPDX-FileCopyrightText: (C) 2020 Francesco Pretto &lt;ceztko@gmail.com&gt;
        /// * SPDX-License-Identifier: MIT-0
        /// */
        ///
        ///#ifndef CB_BINDERUTILS
        ///#define CB_BINDERUTILS
        ///#pragma once
        ///
        ///#import &quot;../CBOCBaseTypes.h&quot;
        ///#include &lt;cstdint&gt;
        ///#include &lt;cinttypes&gt;
        ///#import &lt;Foundation/Foundation.h&gt;
        ///
        ///OCENLIBPDF_API @interface OCBinderUtils : NSObject
        ///+(void)setException:(NSException*)exception;
        ///
        ///+(void)checkException;
        ///
        ///+(void)keepAlive:(NSObject*)obj;
        ///
        ///@end
        ///
        ///inline void* CBGetNativeHandle(CBHandleRef* handl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CBOCBinderUtils_h {
            get {
                return ResourceManager.GetString("CBOCBinderUtils_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * SPDX-FileCopyrightText: (C) 2020 Francesco Pretto &lt;ceztko@gmail.com&gt;
        /// * SPDX-License-Identifier: MIT-0
        /// */
        ///
        ///#import &quot;CBOCBinderUtils.h&quot;
        ///
        ///@implementation OCBinderUtils
        ///
        ///    +(void)setException:(NSException*)exception
        ///    {
        ///        @throw exception;
        ///    }
        ///
        ///    +(void)checkException
        ///    {
        ///        // Do nothing
        ///    }
        ///
        ///    +(void)keepAlive:(NSObject*)obj;
        ///    {
        ///        // Do nothing
        ///    }
        ///@end
        ///.
        /// </summary>
        internal static string CBOCBinderUtils_mm {
            get {
                return ResourceManager.GetString("CBOCBinderUtils_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * SPDX-FileCopyrightText: (C) 2020 Francesco Pretto &lt;ceztko@gmail.com&gt;
        /// * SPDX-License-Identifier: MIT-0
        /// */
        ///
        ///#ifndef CBOCINTEROP_HEADER
        ///#define CBOCINTEROP_HEADER
        ///#pragma once
        ///
        ///#import &lt;Foundation/Foundation.h&gt;
        ///#include &lt;CBInterop.h&gt;
        ///#include &lt;string&gt;
        ///#include &lt;utility&gt;
        ///
        ///#import &quot;CBHandledObject.h&quot;
        ///
        ///class SN2OC
        ///{
        ///private:
        ///    bool m_handled;
        ///    cbstring m_cstr;
        ///    NSString* __strong* m_ocstr;
        ///
        ///public:
        ///    SN2OC(NSString* str)
        ///        : m_handled(false), m_cstr{ }, m_ocstr((N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CBOCInterop_h {
            get {
                return ResourceManager.GetString("CBOCInterop_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once
        ///
        ///#if defined(OBJC_CODEBINDER_SHARED) || !defined(OBJC_CODEBINDER_STATIC)
        ///
        ///#ifdef OBJC_CODEBINDER_EXPORT
        ///    #define OBJC_CODEBINDER_API __attribute__ ((visibility (&quot;default&quot;)))
        ///#else
        ///    #define OBJC_CODEBINDER_IMPORT
        ///    #define OBJC_CODEBINDER_API
        ///#endif
        ///
        ///#else
        ///    #define OBJC_CODEBINDER_API
        ///    #ifndef OBJC_CODEBINDER_EXPORT
        ///        #define OBJC_CODEBINDER_IMPORT
        ///    #endif
        ///#endif
        ///.
        /// </summary>
        internal static string cboclibdefs_h {
            get {
                return ResourceManager.GetString("cboclibdefs_h", resourceCulture);
            }
        }
    }
}
