# The JNI trampolines generated by CodeBinder resolve these types and members by
# name at runtime, for example:
#   FindClass("CodeBinder/HandleRef") + GetFieldID(cls, "handle", "J")
#   GetFieldID(cls, "value", ...) on the CodeBinder.*Box types
#   Java_CodeBinder_BinderUtils_* native entry points
# so nothing in this package may be renamed or removed by R8/ProGuard.
-keep class CodeBinder.** { *; }
-keepclasseswithmembernames class CodeBinder.** {
    native <methods>;
}
