//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTranslator.JNI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JNIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JNIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeTranslator.JNI.Resources.JNIResources", typeof(JNIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &quot;JNIBoxes.h&quot;
        ///
        ///JB2NImpl&lt;jBooleanBox, jboolean&gt; JB2N(JNIEnv * env, jBooleanBox box, bool commit)
        ///{
        ///    return JB2NImpl&lt;jBooleanBox, jboolean&gt;(env, box, commit);
        ///}
        ///
        ///JB2NImpl&lt;jCharacterBox, jchar&gt; JB2N(JNIEnv * env, jCharacterBox box, bool commit)
        ///{
        ///    return JB2NImpl&lt;jCharacterBox, jchar&gt;(env, box, commit);
        ///}
        ///
        ///JB2NImpl&lt;jByteBox, jbyte&gt; JB2N(JNIEnv * env, jByteBox box, bool commit)
        ///{
        ///    return JB2NImpl&lt;jByteBox, jbyte&gt;(env, box, commit);
        ///}
        ///
        ///JB2NImpl&lt;jShortBox, jshort&gt; JB2N(JNIEnv * e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JNIBoxes_cpp {
            get {
                return ResourceManager.GetString("JNIBoxes_cpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once
        ///
        ///#include &quot;JNIBoxesTemplate.h&quot;
        ///
        ///JB2NImpl&lt;jBooleanBox, jboolean&gt; JB2N(JNIEnv *env, jBooleanBox box, bool commit = false);
        ///JB2NImpl&lt;jCharacterBox, jchar&gt; JB2N(JNIEnv *env, jCharacterBox box, bool commit = false);
        ///JB2NImpl&lt;jByteBox, jbyte&gt; JB2N(JNIEnv *env, jByteBox box, bool commit = false);
        ///JB2NImpl&lt;jShortBox, jshort&gt; JB2N(JNIEnv *env, jShortBox box, bool commit = false);
        ///JB2NImpl&lt;jIntegerBox, jint&gt; JB2N(JNIEnv *env, jIntegerBox box, bool commit = false);
        ///JB2NImpl&lt;jLongBox, jlong&gt; JB2N( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JNIBoxes_h {
            get {
                return ResourceManager.GetString("JNIBoxes_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once
        ///
        ///#include &lt;stdexcept&gt;
        ///#include &quot;JNITypesPrivate.h&quot;
        ///
        ///// Wraps custom java box type
        ///template &lt;typename TJBox, typename T&gt;
        ///class JB2NImpl
        ///{
        ///public:
        ///    JB2NImpl(JNIEnv *env, TJBox box, bool commit);
        ///    ~JB2NImpl();
        ///public:
        ///    inline operator T *() const { return &amp;Value; }
        ///public:
        ///    T Value;
        ///private:
        ///    JNIEnv *m_env;
        ///    TJBox m_box;
        ///    bool m_commit;
        ///};
        ///
        ///template&lt;typename TJBox, typename T&gt;
        ///JB2NImpl&lt;TJBox, T&gt;::JB2NImpl(JNIEnv *env, TJBox box, bool commit)
        ///{
        ///    m_en [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JNIBoxesTemplate {
            get {
                return ResourceManager.GetString("JNIBoxesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &quot;JNITypesPrivate.h&quot;
        ///
        ///const char * _jBooleanBoxBase::getFieldIdSignature()
        ///{
        ///    return &quot;Z&quot;;
        ///}
        ///
        ///jboolean _jBooleanBoxBase::getValue(JNIEnv * env, jfieldID field) const
        ///{
        ///    return env-&gt;GetBooleanField((jobject)this, field);
        ///}
        ///
        ///void _jBooleanBoxBase::setValue(JNIEnv * env, jfieldID field, jboolean value)
        ///{
        ///    env-&gt;SetBooleanField(this, field, value);
        ///}
        ///
        ///const char * _jCharacterBoxBase::getFieldIdSignature()
        ///{
        ///    return &quot;C&quot;;
        ///}
        ///
        ///jchar _jCharacterBoxBase::getValue(JNIEnv * env,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JNITypes_cpp {
            get {
                return ResourceManager.GetString("JNITypes_cpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once
        ///
        ///#include &lt;jni.h&gt;
        ///
        ///#define jBooleanBox jobject
        ///#define jCharacterBox jobject
        ///#define jByteBox jobject
        ///#define jShortBox jobject
        ///#define jIntegerBox jobject
        ///#define jLongBox jobject
        ///#define jFloatBox jobject
        ///#define jDoubleBox jobject
        ///#define jStringBox jobject
        ///.
        /// </summary>
        internal static string JNITypes_h {
            get {
                return ResourceManager.GetString("JNITypes_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once
        ///
        ///#include &quot;JNITypes.h&quot;
        ///
        ///#undef jBooleanBox
        ///#undef jCharacterBox
        ///#undef jByteBox
        ///#undef jShortBox
        ///#undef jIntegerBox
        ///#undef jLongBox
        ///#undef jFloatBox
        ///#undef jDoubleBox
        ///#undef jStringBox
        ///
        ///// Template for box types
        ///template &lt;typename BaseT&gt;
        ///class _jTypeBox : public BaseT
        ///{
        ///public:
        ///    typename BaseT::Type GetValue(JNIEnv *env) const;
        ///    void SetValue(JNIEnv *env, typename BaseT::Type value);
        ///private:
        ///    jfieldID getFieldId(JNIEnv *env) const;
        ///};
        ///
        ///////////////////////
        ///// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JNITypesPrivate {
            get {
                return ResourceManager.GetString("JNITypesPrivate", resourceCulture);
            }
        }
    }
}
